// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-fetch';
import type { GetCategoryTreeData, GetCategoryTreeResponse, GetCategoryTreeError, CreateCategoryData, CreateCategoryResponse, CreateCategoryError, DeleteCategoryData, DeleteCategoryError, GetCategoryData, GetCategoryResponse, GetCategoryError, RenameCategoryData, RenameCategoryError, GetCategoryItemsData, GetCategoryItemsResponse, GetCategoryItemsError, SetCategoryParentData, SetCategoryParentError, GetUserInfoData, GetUserInfoResponse, GetAllItemsData, GetAllItemsResponse, GetAllItemsError, CreateItemData, CreateItemResponse, CreateItemError, GetItemData, GetItemResponse, GetItemError, ReserveItemData, ReserveItemError, BorrowItemData, BorrowItemError, BorrowReservationData, BorrowReservationError, ReturnItemData, ReturnItemError, CancelReservationData, CancelReservationError, GetStoragesData, GetStoragesResponse, GetStoragesError, CreateStorageData, CreateStorageResponse, CreateStorageError, GetRootStorageData, GetRootStorageResponse, GetRootStorageError, GetStorageData, GetStorageResponse, GetStorageError, GetStorageBySlugData, GetStorageBySlugResponse, GetStorageBySlugError, GetStorageTypesData, GetStorageTypesResponse, GetStorageTypesError, CreateStorageTypeData, CreateStorageTypeResponse, CreateStorageTypeError } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
};

export const getCategoryTree = <ThrowOnError extends boolean = false>(options?: Options<GetCategoryTreeData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetCategoryTreeResponse, GetCategoryTreeError, ThrowOnError>({
        url: '/api/categories',
        ...options
    });
};

export const createCategory = <ThrowOnError extends boolean = false>(options?: Options<CreateCategoryData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<CreateCategoryResponse, CreateCategoryError, ThrowOnError>({
        url: '/api/categories',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

export const deleteCategory = <ThrowOnError extends boolean = false>(options: Options<DeleteCategoryData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<unknown, DeleteCategoryError, ThrowOnError>({
        url: '/api/categories/{id}',
        ...options
    });
};

export const getCategory = <ThrowOnError extends boolean = false>(options: Options<GetCategoryData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetCategoryResponse, GetCategoryError, ThrowOnError>({
        url: '/api/categories/{id}',
        ...options
    });
};

export const renameCategory = <ThrowOnError extends boolean = false>(options: Options<RenameCategoryData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).put<unknown, RenameCategoryError, ThrowOnError>({
        url: '/api/categories/{id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

export const getCategoryItems = <ThrowOnError extends boolean = false>(options: Options<GetCategoryItemsData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetCategoryItemsResponse, GetCategoryItemsError, ThrowOnError>({
        url: '/api/categories/{id}/items',
        ...options
    });
};

export const setCategoryParent = <ThrowOnError extends boolean = false>(options: Options<SetCategoryParentData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<unknown, SetCategoryParentError, ThrowOnError>({
        url: '/api/categories/{id}/setParent/{parentId}',
        ...options
    });
};

export const getUserInfo = <ThrowOnError extends boolean = false>(options?: Options<GetUserInfoData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetUserInfoResponse, unknown, ThrowOnError>({
        url: '/api/user',
        ...options
    });
};

export const getAllItems = <ThrowOnError extends boolean = false>(options?: Options<GetAllItemsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetAllItemsResponse, GetAllItemsError, ThrowOnError>({
        url: '/api/items',
        ...options
    });
};

export const createItem = <ThrowOnError extends boolean = false>(options?: Options<CreateItemData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<CreateItemResponse, CreateItemError, ThrowOnError>({
        url: '/api/items',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

export const getItem = <ThrowOnError extends boolean = false>(options: Options<GetItemData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetItemResponse, GetItemError, ThrowOnError>({
        url: '/api/items/{id}',
        ...options
    });
};

export const reserveItem = <ThrowOnError extends boolean = false>(options: Options<ReserveItemData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<unknown, ReserveItemError, ThrowOnError>({
        url: '/api/items/{id}/reserve',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

export const borrowItem = <ThrowOnError extends boolean = false>(options: Options<BorrowItemData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<unknown, BorrowItemError, ThrowOnError>({
        url: '/api/items/{id}/borrow',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

export const borrowReservation = <ThrowOnError extends boolean = false>(options: Options<BorrowReservationData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<unknown, BorrowReservationError, ThrowOnError>({
        url: '/api/items/{id}/borrowReservation',
        ...options
    });
};

export const returnItem = <ThrowOnError extends boolean = false>(options: Options<ReturnItemData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<unknown, ReturnItemError, ThrowOnError>({
        url: '/api/items/{id}/return',
        ...options
    });
};

export const cancelReservation = <ThrowOnError extends boolean = false>(options: Options<CancelReservationData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<unknown, CancelReservationError, ThrowOnError>({
        url: '/api/items/{id}/cancelReservation',
        ...options
    });
};

export const getStorages = <ThrowOnError extends boolean = false>(options?: Options<GetStoragesData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetStoragesResponse, GetStoragesError, ThrowOnError>({
        url: '/api/storages',
        ...options
    });
};

export const createStorage = <ThrowOnError extends boolean = false>(options?: Options<CreateStorageData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<CreateStorageResponse, CreateStorageError, ThrowOnError>({
        url: '/api/storages',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

export const getRootStorage = <ThrowOnError extends boolean = false>(options?: Options<GetRootStorageData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetRootStorageResponse, GetRootStorageError, ThrowOnError>({
        url: '/api/storages/root',
        ...options
    });
};

export const getStorage = <ThrowOnError extends boolean = false>(options: Options<GetStorageData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetStorageResponse, GetStorageError, ThrowOnError>({
        url: '/api/storages/{id}',
        ...options
    });
};

export const getStorageBySlug = <ThrowOnError extends boolean = false>(options: Options<GetStorageBySlugData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetStorageBySlugResponse, GetStorageBySlugError, ThrowOnError>({
        url: '/api/storages/slug/{slug}',
        ...options
    });
};

export const getStorageTypes = <ThrowOnError extends boolean = false>(options?: Options<GetStorageTypesData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetStorageTypesResponse, GetStorageTypesError, ThrowOnError>({
        url: '/api/storageTypes',
        ...options
    });
};

export const createStorageType = <ThrowOnError extends boolean = false>(options?: Options<CreateStorageTypeData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<CreateStorageTypeResponse, CreateStorageTypeError, ThrowOnError>({
        url: '/api/storageTypes',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};