// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { BorrowItemData, BorrowItemErrors, BorrowItemResponses, BorrowReservationData, BorrowReservationErrors, BorrowReservationResponses, CancelReservationData, CancelReservationErrors, CancelReservationResponses, CreateCategoryData, CreateCategoryErrors, CreateCategoryResponses, CreateItemData, CreateItemErrors, CreateItemResponses, CreateStorageData, CreateStorageErrors, CreateStorageResponses, CreateStorageTypeData, CreateStorageTypeErrors, CreateStorageTypeResponses, DeleteCategoryData, DeleteCategoryErrors, DeleteCategoryResponses, GetAllItemsData, GetAllItemsErrors, GetAllItemsResponses, GetCategoryData, GetCategoryErrors, GetCategoryItemsData, GetCategoryItemsErrors, GetCategoryItemsResponses, GetCategoryResponses, GetCategoryTreeData, GetCategoryTreeErrors, GetCategoryTreeResponses, GetItemData, GetItemErrors, GetItemResponses, GetLoggedInUserInfoData, GetLoggedInUserInfoResponses, GetRootStorageData, GetRootStorageErrors, GetRootStorageResponses, GetStorageBySlugData, GetStorageBySlugErrors, GetStorageBySlugResponses, GetStorageData, GetStorageErrors, GetStorageResponses, GetStoragesData, GetStoragesErrors, GetStoragesResponses, GetStorageTypesData, GetStorageTypesErrors, GetStorageTypesResponses, GetUserInfoData, GetUserInfoResponses, RenameCategoryData, RenameCategoryErrors, RenameCategoryResponses, ReserveItemData, ReserveItemErrors, ReserveItemResponses, ReturnItemData, ReturnItemErrors, ReturnItemResponses, SetCategoryParentData, SetCategoryParentErrors, SetCategoryParentResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const getUserInfo = <ThrowOnError extends boolean = false>(options?: Options<GetUserInfoData, ThrowOnError>) => (options?.client ?? client).get<GetUserInfoResponses, unknown, ThrowOnError>({ url: '/api/user', ...options });

export const getLoggedInUserInfo = <ThrowOnError extends boolean = false>(options?: Options<GetLoggedInUserInfoData, ThrowOnError>) => (options?.client ?? client).get<GetLoggedInUserInfoResponses, unknown, ThrowOnError>({ url: '/api/user/login', ...options });

export const getCategoryTree = <ThrowOnError extends boolean = false>(options?: Options<GetCategoryTreeData, ThrowOnError>) => (options?.client ?? client).get<GetCategoryTreeResponses, GetCategoryTreeErrors, ThrowOnError>({ url: '/api/categories', ...options });

export const createCategory = <ThrowOnError extends boolean = false>(options?: Options<CreateCategoryData, ThrowOnError>) => (options?.client ?? client).post<CreateCategoryResponses, CreateCategoryErrors, ThrowOnError>({
    url: '/api/categories',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const deleteCategory = <ThrowOnError extends boolean = false>(options: Options<DeleteCategoryData, ThrowOnError>) => (options.client ?? client).delete<DeleteCategoryResponses, DeleteCategoryErrors, ThrowOnError>({ url: '/api/categories/{id}', ...options });

export const getCategory = <ThrowOnError extends boolean = false>(options: Options<GetCategoryData, ThrowOnError>) => (options.client ?? client).get<GetCategoryResponses, GetCategoryErrors, ThrowOnError>({ url: '/api/categories/{id}', ...options });

export const renameCategory = <ThrowOnError extends boolean = false>(options: Options<RenameCategoryData, ThrowOnError>) => (options.client ?? client).put<RenameCategoryResponses, RenameCategoryErrors, ThrowOnError>({
    url: '/api/categories/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getCategoryItems = <ThrowOnError extends boolean = false>(options: Options<GetCategoryItemsData, ThrowOnError>) => (options.client ?? client).get<GetCategoryItemsResponses, GetCategoryItemsErrors, ThrowOnError>({ url: '/api/categories/{id}/items', ...options });

export const setCategoryParent = <ThrowOnError extends boolean = false>(options: Options<SetCategoryParentData, ThrowOnError>) => (options.client ?? client).post<SetCategoryParentResponses, SetCategoryParentErrors, ThrowOnError>({ url: '/api/categories/{id}/setParent/{parentId}', ...options });

export const getStorageTypes = <ThrowOnError extends boolean = false>(options?: Options<GetStorageTypesData, ThrowOnError>) => (options?.client ?? client).get<GetStorageTypesResponses, GetStorageTypesErrors, ThrowOnError>({ url: '/api/storageTypes', ...options });

export const createStorageType = <ThrowOnError extends boolean = false>(options?: Options<CreateStorageTypeData, ThrowOnError>) => (options?.client ?? client).post<CreateStorageTypeResponses, CreateStorageTypeErrors, ThrowOnError>({
    url: '/api/storageTypes',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const getStorages = <ThrowOnError extends boolean = false>(options?: Options<GetStoragesData, ThrowOnError>) => (options?.client ?? client).get<GetStoragesResponses, GetStoragesErrors, ThrowOnError>({ url: '/api/storages', ...options });

export const createStorage = <ThrowOnError extends boolean = false>(options?: Options<CreateStorageData, ThrowOnError>) => (options?.client ?? client).post<CreateStorageResponses, CreateStorageErrors, ThrowOnError>({
    url: '/api/storages',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const getRootStorage = <ThrowOnError extends boolean = false>(options?: Options<GetRootStorageData, ThrowOnError>) => (options?.client ?? client).get<GetRootStorageResponses, GetRootStorageErrors, ThrowOnError>({ url: '/api/storages/root', ...options });

export const getStorage = <ThrowOnError extends boolean = false>(options: Options<GetStorageData, ThrowOnError>) => (options.client ?? client).get<GetStorageResponses, GetStorageErrors, ThrowOnError>({ url: '/api/storages/{id}', ...options });

export const getStorageBySlug = <ThrowOnError extends boolean = false>(options: Options<GetStorageBySlugData, ThrowOnError>) => (options.client ?? client).get<GetStorageBySlugResponses, GetStorageBySlugErrors, ThrowOnError>({ url: '/api/storages/slug/{slug}', ...options });

export const getAllItems = <ThrowOnError extends boolean = false>(options?: Options<GetAllItemsData, ThrowOnError>) => (options?.client ?? client).get<GetAllItemsResponses, GetAllItemsErrors, ThrowOnError>({ url: '/api/items', ...options });

export const createItem = <ThrowOnError extends boolean = false>(options?: Options<CreateItemData, ThrowOnError>) => (options?.client ?? client).post<CreateItemResponses, CreateItemErrors, ThrowOnError>({
    url: '/api/items',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const getItem = <ThrowOnError extends boolean = false>(options: Options<GetItemData, ThrowOnError>) => (options.client ?? client).get<GetItemResponses, GetItemErrors, ThrowOnError>({ url: '/api/items/{id}', ...options });

export const reserveItem = <ThrowOnError extends boolean = false>(options: Options<ReserveItemData, ThrowOnError>) => (options.client ?? client).post<ReserveItemResponses, ReserveItemErrors, ThrowOnError>({
    url: '/api/items/{id}/reserve',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const borrowItem = <ThrowOnError extends boolean = false>(options: Options<BorrowItemData, ThrowOnError>) => (options.client ?? client).post<BorrowItemResponses, BorrowItemErrors, ThrowOnError>({
    url: '/api/items/{id}/borrow',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const borrowReservation = <ThrowOnError extends boolean = false>(options: Options<BorrowReservationData, ThrowOnError>) => (options.client ?? client).post<BorrowReservationResponses, BorrowReservationErrors, ThrowOnError>({ url: '/api/items/{id}/borrowReservation', ...options });

export const returnItem = <ThrowOnError extends boolean = false>(options: Options<ReturnItemData, ThrowOnError>) => (options.client ?? client).post<ReturnItemResponses, ReturnItemErrors, ThrowOnError>({ url: '/api/items/{id}/return', ...options });

export const cancelReservation = <ThrowOnError extends boolean = false>(options: Options<CancelReservationData, ThrowOnError>) => (options.client ?? client).post<CancelReservationResponses, CancelReservationErrors, ThrowOnError>({ url: '/api/items/{id}/cancelReservation', ...options });
