// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:5231/' | (string & {});
};

export type AddItemCode = {
    codeType: CodeType;
    contents: string;
    id: number;
};

export type BorrowingDto = {
    status?: BorrowingStatus;
    start?: null | string;
    end?: null | string;
    update?: null | string;
    borrower: string;
    comment?: null | string;
    incomplete?: boolean;
};

export type BorrowingStatus = number;

export type BorrowItem = {
    borrowerName: string;
    expectedReturn: string;
    incomplete: boolean;
    comment: null | string;
    id: number;
};

export type CategoryDto = {
    id?: number;
    parentId?: null | number;
    name: string;
    slug?: null | string;
};

export type CategoryTreeResponse = {
    id?: number;
    parentId?: null | number;
    name: string;
    slug?: null | string;
    children?: Array<CategoryTreeResponse>;
};

export type CodeType = number;

export type CreateCategory = {
    name: string;
    parentId: null | number;
    slug: null | string;
};

export type CreateItem = {
    name: string;
    categoryId: number;
    storageId: number;
    slug: null | string;
    quantityType?: QuantityType;
    expiresAt?: null | string;
};

export type CreateStorage = {
    name: string;
    storageTypeId: number;
    slug: null | string;
    parentId: null | number;
};

export type CreateStorageType = {
    name: string;
};

export type CreateTag = {
    name: string;
};

export type Error = {
    code: string;
    message: string;
};

export type ErrorResponse = {
    errors: Array<Error>;
};

export type IFormFile = Blob | File;

export type ImageDto = {
    id?: number;
    url: string;
    order?: number;
};

export type ItemCodeDto = {
    id: number;
    codeType: CodeType;
    contents: string;
};

export type ItemListEntry = {
    id?: number;
    name: string;
    slug?: null | string;
    quantityType?: QuantityType;
    quantity?: null | number;
    level?: null | QuantityLevel;
    broken?: boolean;
    borrowed?: boolean;
    addedAt?: string;
    expiresAt?: null | string;
    tags?: Array<string>;
};

export type ItemResponse = {
    id?: number;
    slug?: null | string;
    name: string;
    quantityType?: QuantityType;
    quantity?: null | number;
    level?: null | QuantityLevel;
    storage: StorageListEntry;
    category: CategoryDto;
    note?: null | string;
    broken?: boolean;
    addedAt?: string;
    expiresAt?: null | string;
    borrowings?: Array<BorrowingDto>;
    tags?: Array<string>;
    codes?: Array<ItemCodeDto>;
    images?: Array<ImageDto>;
};

export type NotFoundResponse = {
    missingEntity: string;
};

export type QuantityLevel = number;

export type QuantityType = number;

export type RenameCategory = {
    name: string;
    id: number;
};

export type RenameStorageType = {
    name: string;
    id: number;
};

export type ReserveItem = {
    borrowerName: string;
    expectedStart: string;
    expectedReturn: string;
    incomplete: boolean;
    comment: null | string;
    id: number;
};

export type SetCategoryParent = {
    parentId: null | number;
    id: number;
};

export type SetItemTags = {
    tagIds: Array<number>;
    id: number;
};

export type SetStorageParent = {
    parentId: null | number;
    id: number;
};

export type StorageItemsResponse = {
    id?: number;
    name: string;
    type: StorageTypeDto;
    parentId?: null | number;
    parentSlug?: null | string;
    childStorages?: Array<StorageListEntry>;
    items?: Array<ItemListEntry>;
    images?: Array<ImageDto>;
};

export type StorageListEntry = {
    id?: number;
    name: string;
    slug?: null | string;
    type: StorageTypeDto;
};

export type StorageTreeResponse = {
    id?: number;
    parentId?: null | number;
    storageTypeId?: number;
    name: string;
    children?: Array<StorageTreeResponse>;
};

export type StorageTypeDto = {
    id?: number;
    name: string;
};

export type TagDto = {
    id?: number;
    name: string;
};

export type UpdateItem = {
    name: string;
    slug: null | string;
    note: null | string;
    categoryId: number;
    storageId: number;
    quantityType: QuantityType;
    quantity: null | number;
    broken: boolean;
    expiresAt?: null | string;
    id: number;
};

export type UpdateItemCode = {
    codeType: CodeType;
    contents: string;
    id: number;
    codeId: number;
};

export type UpdateStorage = {
    name: string;
    storageTypeId: number;
    id: number;
};

export type UserInfoDto = {
    authorized?: boolean;
    name?: null | string;
    username?: null | string;
};

export type GetUserInfoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/user';
};

export type GetUserInfoResponses = {
    /**
     * OK
     */
    200: UserInfoDto;
};

export type GetUserInfoResponse = GetUserInfoResponses[keyof GetUserInfoResponses];

export type GetLoggedInUserInfoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/user/login';
};

export type GetLoggedInUserInfoResponses = {
    /**
     * OK
     */
    200: UserInfoDto;
};

export type GetLoggedInUserInfoResponse = GetLoggedInUserInfoResponses[keyof GetLoggedInUserInfoResponses];

export type UploadItemImageData = {
    body: {
        file: IFormFile;
    };
    path: {
        id: number;
    };
    query?: never;
    url: '/api/items/{id}/images';
};

export type UploadItemImageResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteItemImageData = {
    body?: never;
    path: {
        id: number;
        imageId: number;
    };
    query?: never;
    url: '/api/items/{id}/images/{imageId}';
};

export type DeleteItemImageResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ReorderItemImagesData = {
    body: Array<number>;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/items/{id}/images/order';
};

export type ReorderItemImagesResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type UploadStorageImageData = {
    body: {
        file: IFormFile;
    };
    path: {
        id: number;
    };
    query?: never;
    url: '/api/storages/{id}/images';
};

export type UploadStorageImageResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteStorageImageData = {
    body?: never;
    path: {
        id: number;
        imageId: number;
    };
    query?: never;
    url: '/api/storages/{id}/images/{imageId}';
};

export type DeleteStorageImageResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ReorderStorageImagesData = {
    body: Array<number>;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/storages/{id}/images/order';
};

export type ReorderStorageImagesResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetImageData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/images/{id}';
};

export type GetImageResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetCategoryTreeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/categories';
};

export type GetCategoryTreeErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Not Found
     */
    404: NotFoundResponse;
};

export type GetCategoryTreeError = GetCategoryTreeErrors[keyof GetCategoryTreeErrors];

export type GetCategoryTreeResponses = {
    /**
     * OK
     */
    200: Array<CategoryTreeResponse>;
};

export type GetCategoryTreeResponse = GetCategoryTreeResponses[keyof GetCategoryTreeResponses];

export type CreateCategoryData = {
    body?: CreateCategory;
    path?: never;
    query?: never;
    url: '/api/categories';
};

export type CreateCategoryErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Not Found
     */
    404: NotFoundResponse;
};

export type CreateCategoryError = CreateCategoryErrors[keyof CreateCategoryErrors];

export type CreateCategoryResponses = {
    /**
     * OK
     */
    200: number;
};

export type CreateCategoryResponse = CreateCategoryResponses[keyof CreateCategoryResponses];

export type DeleteCategoryData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/categories/{id}';
};

export type DeleteCategoryErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Not Found
     */
    404: NotFoundResponse;
};

export type DeleteCategoryError = DeleteCategoryErrors[keyof DeleteCategoryErrors];

export type DeleteCategoryResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetCategoryData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/categories/{id}';
};

export type GetCategoryErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Not Found
     */
    404: NotFoundResponse;
};

export type GetCategoryError = GetCategoryErrors[keyof GetCategoryErrors];

export type GetCategoryResponses = {
    /**
     * OK
     */
    200: CategoryDto;
};

export type GetCategoryResponse = GetCategoryResponses[keyof GetCategoryResponses];

export type RenameCategoryData = {
    body: RenameCategory;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/categories/{id}';
};

export type RenameCategoryErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Not Found
     */
    404: NotFoundResponse;
};

export type RenameCategoryError = RenameCategoryErrors[keyof RenameCategoryErrors];

export type RenameCategoryResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetCategoryItemsData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/categories/{id}/items';
};

export type GetCategoryItemsErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Not Found
     */
    404: NotFoundResponse;
};

export type GetCategoryItemsError = GetCategoryItemsErrors[keyof GetCategoryItemsErrors];

export type GetCategoryItemsResponses = {
    /**
     * OK
     */
    200: Array<ItemListEntry>;
};

export type GetCategoryItemsResponse = GetCategoryItemsResponses[keyof GetCategoryItemsResponses];

export type SetCategoryParentData = {
    body: SetCategoryParent;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/categories/{id}/setParent';
};

export type SetCategoryParentErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Not Found
     */
    404: NotFoundResponse;
};

export type SetCategoryParentError = SetCategoryParentErrors[keyof SetCategoryParentErrors];

export type SetCategoryParentResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetStorageTypesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/storageTypes';
};

export type GetStorageTypesErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Not Found
     */
    404: NotFoundResponse;
};

export type GetStorageTypesError = GetStorageTypesErrors[keyof GetStorageTypesErrors];

export type GetStorageTypesResponses = {
    /**
     * OK
     */
    200: Array<StorageTypeDto>;
};

export type GetStorageTypesResponse = GetStorageTypesResponses[keyof GetStorageTypesResponses];

export type CreateStorageTypeData = {
    body?: CreateStorageType;
    path?: never;
    query?: never;
    url: '/api/storageTypes';
};

export type CreateStorageTypeErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Not Found
     */
    404: NotFoundResponse;
};

export type CreateStorageTypeError = CreateStorageTypeErrors[keyof CreateStorageTypeErrors];

export type CreateStorageTypeResponses = {
    /**
     * OK
     */
    200: number;
};

export type CreateStorageTypeResponse = CreateStorageTypeResponses[keyof CreateStorageTypeResponses];

export type DeleteStorageTypeData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/storageTypes/{id}';
};

export type DeleteStorageTypeErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Not Found
     */
    404: NotFoundResponse;
};

export type DeleteStorageTypeError = DeleteStorageTypeErrors[keyof DeleteStorageTypeErrors];

export type DeleteStorageTypeResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type RenameStorageTypeData = {
    body: RenameStorageType;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/storageTypes/{id}';
};

export type RenameStorageTypeErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Not Found
     */
    404: NotFoundResponse;
};

export type RenameStorageTypeError = RenameStorageTypeErrors[keyof RenameStorageTypeErrors];

export type RenameStorageTypeResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetTagsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/tags';
};

export type GetTagsErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Not Found
     */
    404: NotFoundResponse;
};

export type GetTagsError = GetTagsErrors[keyof GetTagsErrors];

export type GetTagsResponses = {
    /**
     * OK
     */
    200: Array<TagDto>;
};

export type GetTagsResponse = GetTagsResponses[keyof GetTagsResponses];

export type CreateTagData = {
    body?: CreateTag;
    path?: never;
    query?: never;
    url: '/api/tags';
};

export type CreateTagErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Not Found
     */
    404: NotFoundResponse;
};

export type CreateTagError = CreateTagErrors[keyof CreateTagErrors];

export type CreateTagResponses = {
    /**
     * OK
     */
    200: number;
};

export type CreateTagResponse = CreateTagResponses[keyof CreateTagResponses];

export type DeleteTagData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/tags/{id}';
};

export type DeleteTagErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Not Found
     */
    404: NotFoundResponse;
};

export type DeleteTagError = DeleteTagErrors[keyof DeleteTagErrors];

export type DeleteTagResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetStoragesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/storages';
};

export type GetStoragesErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Not Found
     */
    404: NotFoundResponse;
};

export type GetStoragesError = GetStoragesErrors[keyof GetStoragesErrors];

export type GetStoragesResponses = {
    /**
     * OK
     */
    200: Array<StorageTreeResponse>;
};

export type GetStoragesResponse = GetStoragesResponses[keyof GetStoragesResponses];

export type CreateStorageData = {
    body?: CreateStorage;
    path?: never;
    query?: never;
    url: '/api/storages';
};

export type CreateStorageErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Not Found
     */
    404: NotFoundResponse;
};

export type CreateStorageError = CreateStorageErrors[keyof CreateStorageErrors];

export type CreateStorageResponses = {
    /**
     * OK
     */
    200: number;
};

export type CreateStorageResponse = CreateStorageResponses[keyof CreateStorageResponses];

export type GetRootStorageData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/storages/root';
};

export type GetRootStorageErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Not Found
     */
    404: NotFoundResponse;
};

export type GetRootStorageError = GetRootStorageErrors[keyof GetRootStorageErrors];

export type GetRootStorageResponses = {
    /**
     * OK
     */
    200: Array<StorageListEntry>;
};

export type GetRootStorageResponse = GetRootStorageResponses[keyof GetRootStorageResponses];

export type DeleteStorageData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/storages/{id}';
};

export type DeleteStorageErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Not Found
     */
    404: NotFoundResponse;
};

export type DeleteStorageError = DeleteStorageErrors[keyof DeleteStorageErrors];

export type DeleteStorageResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetStorageData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/storages/{id}';
};

export type GetStorageErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Not Found
     */
    404: NotFoundResponse;
};

export type GetStorageError = GetStorageErrors[keyof GetStorageErrors];

export type GetStorageResponses = {
    /**
     * OK
     */
    200: StorageItemsResponse;
};

export type GetStorageResponse = GetStorageResponses[keyof GetStorageResponses];

export type UpdateStorageData = {
    body: UpdateStorage;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/storages/{id}';
};

export type UpdateStorageErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Not Found
     */
    404: NotFoundResponse;
};

export type UpdateStorageError = UpdateStorageErrors[keyof UpdateStorageErrors];

export type UpdateStorageResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetStorageBySlugData = {
    body?: never;
    path: {
        slug: string;
    };
    query?: never;
    url: '/api/storages/slug/{slug}';
};

export type GetStorageBySlugErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Not Found
     */
    404: NotFoundResponse;
};

export type GetStorageBySlugError = GetStorageBySlugErrors[keyof GetStorageBySlugErrors];

export type GetStorageBySlugResponses = {
    /**
     * OK
     */
    200: StorageItemsResponse;
};

export type GetStorageBySlugResponse = GetStorageBySlugResponses[keyof GetStorageBySlugResponses];

export type SetStorageParentData = {
    body: SetStorageParent;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/storages/{id}/setParent';
};

export type SetStorageParentErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Not Found
     */
    404: NotFoundResponse;
};

export type SetStorageParentError = SetStorageParentErrors[keyof SetStorageParentErrors];

export type SetStorageParentResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetAllItemsData = {
    body?: never;
    path?: never;
    query?: {
        Search?: string;
    };
    url: '/api/items';
};

export type GetAllItemsErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Not Found
     */
    404: NotFoundResponse;
};

export type GetAllItemsError = GetAllItemsErrors[keyof GetAllItemsErrors];

export type GetAllItemsResponses = {
    /**
     * OK
     */
    200: Array<ItemListEntry>;
};

export type GetAllItemsResponse = GetAllItemsResponses[keyof GetAllItemsResponses];

export type CreateItemData = {
    body?: CreateItem;
    path?: never;
    query?: never;
    url: '/api/items';
};

export type CreateItemErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Not Found
     */
    404: NotFoundResponse;
};

export type CreateItemError = CreateItemErrors[keyof CreateItemErrors];

export type CreateItemResponses = {
    /**
     * OK
     */
    200: number;
};

export type CreateItemResponse = CreateItemResponses[keyof CreateItemResponses];

export type GetItemData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/items/{id}';
};

export type GetItemErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Not Found
     */
    404: NotFoundResponse;
};

export type GetItemError = GetItemErrors[keyof GetItemErrors];

export type GetItemResponses = {
    /**
     * OK
     */
    200: ItemResponse;
};

export type GetItemResponse = GetItemResponses[keyof GetItemResponses];

export type UpdateItemData = {
    body: UpdateItem;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/items/{id}';
};

export type UpdateItemErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Not Found
     */
    404: NotFoundResponse;
};

export type UpdateItemError = UpdateItemErrors[keyof UpdateItemErrors];

export type UpdateItemResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type SetItemTagsData = {
    body: SetItemTags;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/items/{id}/tags';
};

export type SetItemTagsErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Not Found
     */
    404: NotFoundResponse;
};

export type SetItemTagsError = SetItemTagsErrors[keyof SetItemTagsErrors];

export type SetItemTagsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type LookupItemByCodeData = {
    body?: never;
    path?: never;
    query: {
        Contents: string;
        CodeType?: CodeType;
    };
    url: '/api/items/byCode';
};

export type LookupItemByCodeErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Not Found
     */
    404: NotFoundResponse;
};

export type LookupItemByCodeError = LookupItemByCodeErrors[keyof LookupItemByCodeErrors];

export type LookupItemByCodeResponses = {
    /**
     * OK
     */
    200: number;
};

export type LookupItemByCodeResponse = LookupItemByCodeResponses[keyof LookupItemByCodeResponses];

export type GetExpiringItemsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/items/expiring';
};

export type GetExpiringItemsErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Not Found
     */
    404: NotFoundResponse;
};

export type GetExpiringItemsError = GetExpiringItemsErrors[keyof GetExpiringItemsErrors];

export type GetExpiringItemsResponses = {
    /**
     * OK
     */
    200: Array<ItemListEntry>;
};

export type GetExpiringItemsResponse = GetExpiringItemsResponses[keyof GetExpiringItemsResponses];

export type AddItemCodeData = {
    body: AddItemCode;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/items/{id}/codes';
};

export type AddItemCodeErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Not Found
     */
    404: NotFoundResponse;
};

export type AddItemCodeError = AddItemCodeErrors[keyof AddItemCodeErrors];

export type AddItemCodeResponses = {
    /**
     * OK
     */
    200: number;
};

export type AddItemCodeResponse = AddItemCodeResponses[keyof AddItemCodeResponses];

export type DeleteItemCodeData = {
    body?: never;
    path: {
        id: number;
        codeId: number;
    };
    query?: never;
    url: '/api/items/{id}/codes/{codeId}';
};

export type DeleteItemCodeErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Not Found
     */
    404: NotFoundResponse;
};

export type DeleteItemCodeError = DeleteItemCodeErrors[keyof DeleteItemCodeErrors];

export type DeleteItemCodeResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type UpdateItemCodeData = {
    body: UpdateItemCode;
    path: {
        id: number;
        codeId: number;
    };
    query?: never;
    url: '/api/items/{id}/codes/{codeId}';
};

export type UpdateItemCodeErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Not Found
     */
    404: NotFoundResponse;
};

export type UpdateItemCodeError = UpdateItemCodeErrors[keyof UpdateItemCodeErrors];

export type UpdateItemCodeResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ReserveItemData = {
    body: ReserveItem;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/items/{id}/reserve';
};

export type ReserveItemErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Not Found
     */
    404: NotFoundResponse;
};

export type ReserveItemError = ReserveItemErrors[keyof ReserveItemErrors];

export type ReserveItemResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type BorrowItemData = {
    body: BorrowItem;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/items/{id}/borrow';
};

export type BorrowItemErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Not Found
     */
    404: NotFoundResponse;
};

export type BorrowItemError = BorrowItemErrors[keyof BorrowItemErrors];

export type BorrowItemResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type BorrowReservationData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/items/{id}/borrowReservation';
};

export type BorrowReservationErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Not Found
     */
    404: NotFoundResponse;
};

export type BorrowReservationError = BorrowReservationErrors[keyof BorrowReservationErrors];

export type BorrowReservationResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ReturnItemData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/items/{id}/return';
};

export type ReturnItemErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Not Found
     */
    404: NotFoundResponse;
};

export type ReturnItemError = ReturnItemErrors[keyof ReturnItemErrors];

export type ReturnItemResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type CancelReservationData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/items/{id}/cancelReservation';
};

export type CancelReservationErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Not Found
     */
    404: NotFoundResponse;
};

export type CancelReservationError = CancelReservationErrors[keyof CancelReservationErrors];

export type CancelReservationResponses = {
    /**
     * OK
     */
    200: unknown;
};
