// This file is auto-generated by @hey-api/openapi-ts

export type BorrowItem = {
    id?: number;
    borrowerName?: string | null;
    expectedReturn?: string;
    incomplete?: boolean;
    comment?: string | null;
};

export type BorrowingDto = {
    status?: BorrowingStatus;
    start?: string | null;
    end?: string | null;
    update?: string | null;
    borrower: string | null;
    comment?: string | null;
    incomplete?: boolean;
};

/**
 *
 *
 * 0 = Cancelled
 *
 * 1 = Reserved
 *
 * 2 = Borrowed
 *
 * 3 = Returned
 */
export type BorrowingStatus = 0 | 1 | 2 | 3;

/**
 *
 *
 * 0 = Cancelled
 *
 * 1 = Reserved
 *
 * 2 = Borrowed
 *
 * 3 = Returned
 */
export const BorrowingStatus = {
    CANCELLED: 0,
    RESERVED: 1,
    BORROWED: 2,
    RETURNED: 3
} as const;

export type CategoryDto = {
    id?: number;
    parentId?: number | null;
    name: string | null;
    slug?: string | null;
};

export type CategoryTreeResponse = {
    id?: number;
    parentId?: number | null;
    name: string | null;
    slug?: string | null;
    children?: Array<CategoryTreeResponse> | null;
};

export type CreateCategory = {
    name?: string | null;
    parentId?: number | null;
    slug?: string | null;
};

export type CreateItem = {
    name?: string | null;
    categoryId?: number;
    storageId?: number;
    slug?: string | null;
};

export type CreateStorage = {
    name?: string | null;
    storageTypeId?: number;
    slug?: string | null;
    parentId?: number | null;
};

export type CreateStorageType = {
    name?: string | null;
};

export type _Error = {
    code?: string | null;
    message?: string | null;
};

export type ErrorResponse = {
    errors?: Array<_Error> | null;
};

export type ItemListEntry = {
    id?: number;
    name: string | null;
    slug?: string | null;
    quantityType?: QuantityType;
    quantity?: number | null;
    level?: QuantityLevel;
    broken?: boolean;
    borrowed?: boolean;
};

export type ItemResponse = {
    id?: number;
    slug?: string | null;
    name: string | null;
    quantityType?: QuantityType;
    quantity?: number | null;
    level?: QuantityLevel;
    storage: StorageListEntry;
    category: CategoryDto;
    note?: string | null;
    borrowings?: Array<BorrowingDto> | null;
};

export type NotFoundResponse = {
    missingEntity?: string | null;
};

/**
 *
 *
 * 0 = None
 *
 * 1 = Low
 *
 * 2 = Good
 */
export type QuantityLevel = 0 | 1 | 2;

/**
 *
 *
 * 0 = None
 *
 * 1 = Low
 *
 * 2 = Good
 */
export const QuantityLevel = {
    NONE: 0,
    LOW: 1,
    GOOD: 2
} as const;

/**
 *
 *
 * 0 = None
 *
 * 1 = Levels
 *
 * 2 = Precise
 */
export type QuantityType = 0 | 1 | 2;

/**
 *
 *
 * 0 = None
 *
 * 1 = Levels
 *
 * 2 = Precise
 */
export const QuantityType = {
    NONE: 0,
    LEVELS: 1,
    PRECISE: 2
} as const;

export type RenameCategory = {
    id?: number;
    name?: string | null;
};

export type ReserveItem = {
    id?: number;
    borrowerName?: string | null;
    expectedStart?: string;
    expectedReturn?: string;
    incomplete?: boolean;
    comment?: string | null;
};

export type StorageItemsResponse = {
    id?: number;
    name: string | null;
    type: StorageType;
    parentId?: number | null;
    parentSlug?: string | null;
    childStorages?: Array<StorageListEntry> | null;
    items?: Array<ItemListEntry> | null;
};

export type StorageListEntry = {
    id?: number;
    name: string | null;
    slug?: string | null;
    type: StorageType;
};

export type StorageTreeResponse = {
    id?: number;
    parentId?: number | null;
    name: string | null;
    children?: Array<StorageTreeResponse> | null;
};

export type StorageType = {
    id?: number;
    name: string | null;
};

export type UserInfoDto = {
    name: string | null;
    username: string | null;
};

export type GetCategoryTreeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/categories';
};

export type GetCategoryTreeErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Not Found
     */
    404: NotFoundResponse;
};

export type GetCategoryTreeError = GetCategoryTreeErrors[keyof GetCategoryTreeErrors];

export type GetCategoryTreeResponses = {
    /**
     * OK
     */
    200: Array<CategoryTreeResponse>;
};

export type GetCategoryTreeResponse = GetCategoryTreeResponses[keyof GetCategoryTreeResponses];

export type CreateCategoryData = {
    body?: CreateCategory;
    path?: never;
    query?: never;
    url: '/api/categories';
};

export type CreateCategoryErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Not Found
     */
    404: NotFoundResponse;
};

export type CreateCategoryError = CreateCategoryErrors[keyof CreateCategoryErrors];

export type CreateCategoryResponses = {
    /**
     * OK
     */
    200: number;
};

export type CreateCategoryResponse = CreateCategoryResponses[keyof CreateCategoryResponses];

export type DeleteCategoryData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/categories/{id}';
};

export type DeleteCategoryErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Not Found
     */
    404: NotFoundResponse;
};

export type DeleteCategoryError = DeleteCategoryErrors[keyof DeleteCategoryErrors];

export type DeleteCategoryResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetCategoryData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/categories/{id}';
};

export type GetCategoryErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Not Found
     */
    404: NotFoundResponse;
};

export type GetCategoryError = GetCategoryErrors[keyof GetCategoryErrors];

export type GetCategoryResponses = {
    /**
     * OK
     */
    200: CategoryDto;
};

export type GetCategoryResponse = GetCategoryResponses[keyof GetCategoryResponses];

export type RenameCategoryData = {
    body: RenameCategory;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/categories/{id}';
};

export type RenameCategoryErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Not Found
     */
    404: NotFoundResponse;
};

export type RenameCategoryError = RenameCategoryErrors[keyof RenameCategoryErrors];

export type RenameCategoryResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetCategoryItemsData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/categories/{id}/items';
};

export type GetCategoryItemsErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Not Found
     */
    404: NotFoundResponse;
};

export type GetCategoryItemsError = GetCategoryItemsErrors[keyof GetCategoryItemsErrors];

export type GetCategoryItemsResponses = {
    /**
     * OK
     */
    200: Array<ItemListEntry>;
};

export type GetCategoryItemsResponse = GetCategoryItemsResponses[keyof GetCategoryItemsResponses];

export type SetCategoryParentData = {
    body?: never;
    path: {
        id: number;
        parentId: number;
    };
    query?: never;
    url: '/api/categories/{id}/setParent/{parentId}';
};

export type SetCategoryParentErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Not Found
     */
    404: NotFoundResponse;
};

export type SetCategoryParentError = SetCategoryParentErrors[keyof SetCategoryParentErrors];

export type SetCategoryParentResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetUserInfoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/user';
};

export type GetUserInfoResponses = {
    /**
     * OK
     */
    200: UserInfoDto;
};

export type GetUserInfoResponse = GetUserInfoResponses[keyof GetUserInfoResponses];

export type GetAllItemsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/items';
};

export type GetAllItemsErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Not Found
     */
    404: NotFoundResponse;
};

export type GetAllItemsError = GetAllItemsErrors[keyof GetAllItemsErrors];

export type GetAllItemsResponses = {
    /**
     * OK
     */
    200: Array<ItemListEntry>;
};

export type GetAllItemsResponse = GetAllItemsResponses[keyof GetAllItemsResponses];

export type CreateItemData = {
    body?: CreateItem;
    path?: never;
    query?: never;
    url: '/api/items';
};

export type CreateItemErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Not Found
     */
    404: NotFoundResponse;
};

export type CreateItemError = CreateItemErrors[keyof CreateItemErrors];

export type CreateItemResponses = {
    /**
     * OK
     */
    200: number;
};

export type CreateItemResponse = CreateItemResponses[keyof CreateItemResponses];

export type GetItemData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/items/{id}';
};

export type GetItemErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Not Found
     */
    404: NotFoundResponse;
};

export type GetItemError = GetItemErrors[keyof GetItemErrors];

export type GetItemResponses = {
    /**
     * OK
     */
    200: ItemResponse;
};

export type GetItemResponse = GetItemResponses[keyof GetItemResponses];

export type ReserveItemData = {
    body: ReserveItem;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/items/{id}/reserve';
};

export type ReserveItemErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Not Found
     */
    404: NotFoundResponse;
};

export type ReserveItemError = ReserveItemErrors[keyof ReserveItemErrors];

export type ReserveItemResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type BorrowItemData = {
    body: BorrowItem;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/items/{id}/borrow';
};

export type BorrowItemErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Not Found
     */
    404: NotFoundResponse;
};

export type BorrowItemError = BorrowItemErrors[keyof BorrowItemErrors];

export type BorrowItemResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type BorrowReservationData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/items/{id}/borrowReservation';
};

export type BorrowReservationErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Not Found
     */
    404: NotFoundResponse;
};

export type BorrowReservationError = BorrowReservationErrors[keyof BorrowReservationErrors];

export type BorrowReservationResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ReturnItemData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/items/{id}/return';
};

export type ReturnItemErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Not Found
     */
    404: NotFoundResponse;
};

export type ReturnItemError = ReturnItemErrors[keyof ReturnItemErrors];

export type ReturnItemResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type CancelReservationData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/items/{id}/cancelReservation';
};

export type CancelReservationErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Not Found
     */
    404: NotFoundResponse;
};

export type CancelReservationError = CancelReservationErrors[keyof CancelReservationErrors];

export type CancelReservationResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetStoragesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/storages';
};

export type GetStoragesErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Not Found
     */
    404: NotFoundResponse;
};

export type GetStoragesError = GetStoragesErrors[keyof GetStoragesErrors];

export type GetStoragesResponses = {
    /**
     * OK
     */
    200: Array<StorageTreeResponse>;
};

export type GetStoragesResponse = GetStoragesResponses[keyof GetStoragesResponses];

export type CreateStorageData = {
    body?: CreateStorage;
    path?: never;
    query?: never;
    url: '/api/storages';
};

export type CreateStorageErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Not Found
     */
    404: NotFoundResponse;
};

export type CreateStorageError = CreateStorageErrors[keyof CreateStorageErrors];

export type CreateStorageResponses = {
    /**
     * OK
     */
    200: number;
};

export type CreateStorageResponse = CreateStorageResponses[keyof CreateStorageResponses];

export type GetRootStorageData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/storages/root';
};

export type GetRootStorageErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Not Found
     */
    404: NotFoundResponse;
};

export type GetRootStorageError = GetRootStorageErrors[keyof GetRootStorageErrors];

export type GetRootStorageResponses = {
    /**
     * OK
     */
    200: Array<StorageListEntry>;
};

export type GetRootStorageResponse = GetRootStorageResponses[keyof GetRootStorageResponses];

export type GetStorageData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/storages/{id}';
};

export type GetStorageErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Not Found
     */
    404: NotFoundResponse;
};

export type GetStorageError = GetStorageErrors[keyof GetStorageErrors];

export type GetStorageResponses = {
    /**
     * OK
     */
    200: StorageItemsResponse;
};

export type GetStorageResponse = GetStorageResponses[keyof GetStorageResponses];

export type GetStorageBySlugData = {
    body?: never;
    path: {
        slug: string;
    };
    query?: never;
    url: '/api/storages/slug/{slug}';
};

export type GetStorageBySlugErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Not Found
     */
    404: NotFoundResponse;
};

export type GetStorageBySlugError = GetStorageBySlugErrors[keyof GetStorageBySlugErrors];

export type GetStorageBySlugResponses = {
    /**
     * OK
     */
    200: StorageItemsResponse;
};

export type GetStorageBySlugResponse = GetStorageBySlugResponses[keyof GetStorageBySlugResponses];

export type GetStorageTypesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/storageTypes';
};

export type GetStorageTypesErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Not Found
     */
    404: NotFoundResponse;
};

export type GetStorageTypesError = GetStorageTypesErrors[keyof GetStorageTypesErrors];

export type GetStorageTypesResponses = {
    /**
     * OK
     */
    200: Array<StorageType>;
};

export type GetStorageTypesResponse = GetStorageTypesResponses[keyof GetStorageTypesResponses];

export type CreateStorageTypeData = {
    body?: CreateStorageType;
    path?: never;
    query?: never;
    url: '/api/storageTypes';
};

export type CreateStorageTypeErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Not Found
     */
    404: NotFoundResponse;
};

export type CreateStorageTypeError = CreateStorageTypeErrors[keyof CreateStorageTypeErrors];

export type CreateStorageTypeResponses = {
    /**
     * OK
     */
    200: number;
};

export type CreateStorageTypeResponse = CreateStorageTypeResponses[keyof CreateStorageTypeResponses];

export type ClientOptions = {
    baseUrl: 'http://localhost:5231' | (string & {});
};